feat: hook now asks for user input if files differ

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -33,17 +33,52 @@ call_conda() {
     conda env export >noodles_temp.yaml &&
     printf "${OVERWRITE}${CHECK_MARK} Exported ${ENVIRONMENT}_temp.yaml\n"
 
-  # Deactivate environment
+  # Deactivate environment, print status
   printf "Deactivating ${ENVIRONMENT}...\n" &&
     conda deactivate &&
     printf "${OVERWRITE}${CHECK_MARK} Deactivated\n"
+}
+
+# get user input to decide whether to push even if file differs
+get_input() {
+  exec </dev/tty # open STDIN to read input
+
+  # read user input
+  while true; do
+    # `read -p` does not support standard formatting. Use `$'...'`
+    read -p $'\033[1;33m?\033[0m Allow push even if file differs? (Y/n) ' yn
+
+    # Blank input == allow push
+    if [ "$yn" = "" ]; then
+      yn='Y'
+    fi
+
+    # check input
+    case "$yn" in
+    [Yy])
+      printf "${CHECK_MARK} Allowing push\n" # Allow push, exit normally
+      return
+      ;;
+    [Nn])
+      printf "${CROSS_MARK} Denying push\n" # Denying push, throw error
+      exit 126                              # "command not executable"
+      ;;
+    *)
+      echo "Please answer 'Y' or 'N'."
+      ;;
+    esac
+  done
+
+  exec <&- # close STDIN
+
+  return
 }
 
 # When exporting the conda environment to the same .yaml file, git will always
 # think that the environment has been changed.
 # Workaround: export to temp file, compare files then act accordingly
 check_diff() {
-  printf "\n"
+  printf "\n" # blank line
 
   if ! cmp -s "./${ENVIRONMENT}.yaml" "./${ENVIRONMENT}_temp.yaml"; then
     # File changed, replace and deny push
@@ -60,12 +95,10 @@ check_diff() {
     printf "${COMMIT_MARK} Committing changes (edit: git commit --amend)\n" &&
       git commit -m "feat(env): auto-updated"
 
-    # Deny push, make user push again
-    # TODO: Add the possibility to push even if files differ
-    printf "${CROSS_MARK} Denying push\n"
+    printf "\n" # blank line
 
-    # Push denied => 126: "command not executable"
-    exit 126
+    # push?
+    get_input
     return
   fi
 
